# -*- coding: utf-8 -*-
"""automate_Aisyah-Azzahrah.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DNmIjd695IUPcKJDXDA1abgVf1WOROr6
"""

# automate_NamaMu.py
# File otomasi preprocessing — Skilled Level

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
import os

def load_data(filepath):
    """Load dataset dari file CSV."""
    print(f'Memuat data dari: {filepath}')
    df = pd.read_csv(filepath)
    print(f'Shape dataset: {df.shape}')
    return df

def handle_missing_values(df):
    """Menangani missing values."""
    # Kolom numerik: isi dengan median
    num_cols = df.select_dtypes(include=[np.number]).columns
    imputer = SimpleImputer(strategy='median')
    df[num_cols] = imputer.fit_transform(df[num_cols])

    # Kolom kategorik: isi dengan modus
    cat_cols = df.select_dtypes(include=['object']).columns
    if len(cat_cols) > 0:
        cat_imputer = SimpleImputer(strategy='most_frequent')
        df[cat_cols] = cat_imputer.fit_transform(df[cat_cols])

    print('Missing values setelah handling:', df.isnull().sum().sum())
    return df

def encode_categorical(df, target_col):
    """Encoding kolom kategorik."""
    cat_cols = df.drop(target_col, axis=1).select_dtypes(include=['object']).columns
    le = LabelEncoder()
    for col in cat_cols:
        df[col] = le.fit_transform(df[col].astype(str))
    print(f'Kolom yang di-encode: {list(cat_cols)}')
    return df

def scale_features(df, target_col):
    """Scaling fitur numerik."""
    X = df.drop(target_col, axis=1)
    y = df[target_col]
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)
    X_scaled = pd.DataFrame(X_scaled, columns=X.columns)
    return X_scaled, y

def preprocess_pipeline(input_path, output_path, target_col):
    """
    Pipeline preprocessing lengkap.
    Returns: X_train, X_test, y_train, y_test
    """
    # Load data
    df = load_data(input_path)

    # Remove duplicates
    df = df.drop_duplicates()

    # Handle missing values
    df = handle_missing_values(df)

    # Encode categorical
    df = encode_categorical(df, target_col)

    # Scale features
    X_scaled, y = scale_features(df, target_col)

    # Gabung kembali
    df_clean = pd.concat([X_scaled, y.reset_index(drop=True)], axis=1)

    # Simpan hasil
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    df_clean.to_csv(output_path, index=False)
    print(f'Dataset tersimpan di: {output_path}')

    # Split data
    X_train, X_test, y_train, y_test = train_test_split(
        X_scaled, y, test_size=0.2, random_state=42)
    return X_train, X_test, y_train, y_test

if __name__ == '__main__':
    # Pastikan path input sesuai dengan nama file di file browser Anda
    # Karena file dataset.csv ada di root folder, gunakan '/content/dataset.csv'
    # Bagian bawah file automate_aisyah_azzahrah.py
X_train, X_test, y_train, y_test = preprocess_pipeline(
    input_path='../namedataset_raw/dataset.csv',
    output_path='namedataset_preprocessing/dataset_clean.csv',  # ← sudah benar, tidak perlu diganti
    target_col='Heart_ stroke'
)
    print('Preprocessing selesai!')
    print('Shape X_train:', X_train.shape)
    print('Shape X_test:', X_test.shape)
